PRODUCT_CATALOG = [
    {
        "id": "kids_daily_essentials",
        "name": "Kids Daily Essentials Multivitamin",
        "profile_types": ["child"],
        "age_groups": ["0_3", "4_8", "9_13"],
        "goals": ["immunity", "energy", "bones"],
        "lifestyle": ["low_veggies", "busy_parent", "picky_eater"],
        "diet_tags": ["vegetarian_friendly"],
        "base_priority": 3,
        # safety
        "min_age": 2,
        "max_age": None,
        "contraindications": [],
        # pricing
        "price_usd": 24.99,
        "servings": 30,
        "subscription_discount": 0.15,
    },
    {
        "id": "kids_probiotic",
        "name": "Kids Probiotic",
        "profile_types": ["child"],
        "age_groups": ["0_3", "4_8", "9_13"],
        "goals": ["gut"],
        "lifestyle": ["picky_eater", "low_veggies"],
        "diet_tags": ["vegetarian_friendly"],
        "base_priority": 2,
        "min_age": 2,
        "max_age": None,
        "contraindications": ["dairy_allergy"],
        "price_usd": 22.99,
        "servings": 30,
        "subscription_discount": 0.15,
    },
    {
        "id": "kids_omega3",
        "name": "Kids Omega-3",
        "profile_types": ["child", "teen"],
        "age_groups": ["4_8", "9_13", "14_18"],
        "goals": ["brain"],
        "lifestyle": ["screen_heavy", "sports"],
        "diet_tags": [],
        "base_priority": 2,
        "min_age": 4,
        "max_age": None,
        "contraindications": ["fish_allergy"],
        "price_usd": 21.99,
        "servings": 30,
        "subscription_discount": 0.15,
    },
    {
        "id": "teen_multivitamin",
        "name": "Teen Multivitamin",
        "profile_types": ["teen"],
        "age_groups": ["9_13", "14_18"],
        "goals": ["immunity", "energy", "bones"],
        "lifestyle": ["sports", "low_veggies"],
        "diet_tags": ["vegetarian_friendly"],
        "base_priority": 3,
        "min_age": 9,
        "max_age": None,
        "contraindications": [],
        "price_usd": 26.99,
        "servings": 30,
        "subscription_discount": 0.15,
    },
    {
        "id": "adult_daily",
        "name": "Adult Daily Multivitamin",
        "profile_types": ["adult_woman", "adult_man"],
        "age_groups": ["19_30", "31_50", "51_plus"],
        "goals": ["immunity", "energy", "bones"],
        "lifestyle": ["low_veggies", "busy_parent"],
        "diet_tags": [],
        "base_priority": 3,
        "min_age": 18,
        "max_age": None,
        "contraindications": [],
        "price_usd": 29.99,
        "servings": 30,
        "subscription_discount": 0.18,
    },
    {
        "id": "iron_b12",
        "name": "Iron + B12 Booster",
        "profile_types": ["adult_woman", "adult_man", "teen"],
        "age_groups": ["14_18", "19_30", "31_50", "51_plus"],
        "goals": ["energy"],
        "lifestyle": [],
        "diet_tags": [],
        "base_priority": 1,
        "min_age": 14,
        "max_age": None,
        "contraindications": [],
        "price_usd": 19.99,
        "servings": 30,
        "subscription_discount": 0.10,
    },
    {
        "id": "magnesium_sleep",
        "name": "Magnesium Sleep Support",
        "profile_types": ["adult_woman", "adult_man"],
        "age_groups": ["19_30", "31_50", "51_plus"],
        "goals": ["sleep"],
        "lifestyle": [],
        "diet_tags": [],
        "base_priority": 1,
        "min_age": 18,
        "max_age": None,
        "contraindications": [],
        "price_usd": 23.99,
        "servings": 30,
        "subscription_discount": 0.15,
    },
    {
        "id": "adult_probiotic",
        "name": "Probiotic + Prebiotic Blend",
        "profile_types": ["adult_woman", "adult_man"],
        "age_groups": ["19_30", "31_50", "51_plus"],
        "goals": ["gut"],
        "lifestyle": ["low_veggies"],
        "diet_tags": [],
        "base_priority": 2,
        "min_age": 18,
        "max_age": None,
        "contraindications": ["dairy_allergy"],
        "price_usd": 27.99,
        "servings": 30,
        "subscription_discount": 0.15,
    },
    {
        "id": "daily_greens",
        "name": "Daily Greens Powder",
        "profile_types": ["adult_woman", "adult_man", "teen"],
        "age_groups": ["14_18", "19_30", "31_50", "51_plus"],
        "goals": ["immunity", "energy", "gut"],
        "lifestyle": ["busy_parent", "low_veggies"],
        "diet_tags": ["vegan_friendly"],
        "base_priority": 0,
        "min_age": 14,
        "max_age": None,
        "contraindications": ["nut_allergy"],
        "price_usd": 32.99,
        "servings": 30,
        "subscription_discount": 0.15,
    },
    {
        "id": "eye_health_omega3",
        "name": "Eye Health Omega-3",
        "profile_types": ["child", "teen", "adult_woman", "adult_man"],
        "age_groups": ["4_8", "9_13", "14_18", "19_30", "31_50", "51_plus"],
        "goals": ["brain"],
        "lifestyle": ["screen_heavy"],
        "diet_tags": [],
        "base_priority": 0,
        "min_age": 4,
        "max_age": None,
        "contraindications": ["fish_allergy"],
        "price_usd": 24.49,
        "servings": 30,
        "subscription_discount": 0.15,
    },
]
